CITY_COORDS = {
    'Gambella': (0, 0),
    'Dembi Dollo': (1, -1),
    'Gimbi': (2, -1),
    'Nekemete': (3, 0),
    'Gore': (1, 1),
    'Tepi': (2, 2),
    'Mezan Teferi': (3, 2),
    'Bonga': (3, 3),
    'Jimma': (4, 3),
    'Bedelle': (4, 1),
    'Dawro': (5, 3),
    'Wolaita Sodo': (6, 3),
    'Arba Minch': (7, 3),
    'Wolkite': (5, 1),
    'Worabe': (6, 1),
    'Hossana': (6, 0),
    'Buta Jirra': (7, 0),
    'Ambo': (4, 0),
    'Addis Ababa': (3, -1),
    'Debre Birhan': (2, -2),
    'Adama': (3, -2),
    'Matahara': (4, -2),
    'Awash': (5, -2),
    'Chiro': (6, -2),
    'Dire Dawa': (7, -2),
    'Harar': (8, -2),
    'Babile': (9, -2),
    'Jigjiga': (10, -2),
    'Dega Habur': (11, -2),
    'Kebri Dehar': (12, -2),
    'Gode': (13, -2),
    'Batu': (5, -1),
    'Shashemene': (6, -1),
    'Hawassa': (7, -1),
    'Dilla': (8, -1),
    'Assella': (4, -3),
    'Assasa': (5, -3),
    'Dodolla': (6, -3),
    'Bale': (7, -3),
    'Goba': (8, -3),
    'Sof Oumer': (9, -3)
}
